version: "3"

services:
  data-analyser:
    build:
      context: ./backend/data-analyser
      dockerfile: Dockerfile
    volumes:
      - /tmp/uploads:/data/uploads:ro,z
    depends_on:
      - nats
    networks:
      - fap-network

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - fap-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fap_analysis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fap-network

networks:
  fap-network:
    driver: bridge

volumes:
  postgres_data:
