# Generic Docker commands
.PHONY: docker-prod docker-local docker-k3d docker-next-tag

# Docker configuration
DOCKER_IMAGE_NAME ?= $(error DOCKER_IMAGE_NAME must be set)
TAG_PREFIX ?= 1.0.
MAKEFILE_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
DOCKER_HELPERS_SCRIPT ?= $(MAKEFILE_DIR)/docker-helpers.py

docker-next-tag:
	@if [ -z "$(DOCKER_IMAGE_NAME)" ]; then \
		echo "Error: DOCKER_IMAGE_NAME must be set"; \
		exit 1; \
	fi
	@DOCKER_IMAGE_NAME="$(DOCKER_IMAGE_NAME)" TAG_PREFIX="$(TAG_PREFIX)" python3 "$(DOCKER_HELPERS_SCRIPT)" next-tag

# Build and push Docker image to remote registry
# Usage: make docker-prod tag=TAG
docker-prod:
	@tag="$(tag)"; \
	if [ -z "$$tag" ]; then \
		tag=$$(DOCKER_IMAGE_NAME="$(DOCKER_IMAGE_NAME)" TAG_PREFIX="$(TAG_PREFIX)" $(MAKE) --no-print-directory -s docker-next-tag); \
		if [ -z "$$tag" ]; then \
			echo "Error: Unable to determine image tag. Usage: make docker-prod tag=TAG"; \
			exit 1; \
		fi; \
		echo "Info: Using autogenerated tag $$tag"; \
	fi; \
	docker buildx build --platform linux/amd64,linux/arm64 -t $(DOCKER_IMAGE_NAME):$$tag --push .

# Build and push Docker image to local registry
# Usage: make docker-local tag=TAG
docker-local:
	@if [ -z "$(tag)" ]; then \
		echo "Error: Tag is required. Usage: make docker-local tag=TAG"; \
		exit 1; \
	fi
	docker build -t $(DOCKER_IMAGE_NAME):$(tag) .

# Build local image and import to k3d cluster
# Usage: make docker-k3d tag=TAG
docker-k3d: docker-local
	@if [ -z "$(tag)" ]; then \
		echo "Error: Tag is required. Usage: make docker-k3d tag=TAG"; \
		exit 1; \
	fi
	docker exec k3d-fap-server-0 sh -c "ctr image rm \$$(ctr image list -q | grep $(DOCKER_IMAGE_NAME) | head -1)" || true
	k3d image import $(DOCKER_IMAGE_NAME):$(tag) -c fap
